// GENERATED CODE - DO NOT MODIFY BY HAND

part of 'model.dart';

// **************************************************************************
// SqfEntityGenerator
// **************************************************************************

// ignore_for_file: non_constant_identifier_names

//  These classes was generated by SqfEntity
//  Copyright (c) 2019, All rights reserved. Use of this source code is governed by a
//  Apache license that can be found in the LICENSE file.

//  To use these SqfEntity classes do following:
//  - import model.dart into where to use
//  - start typing ex:Milestone.select()... (add a few filters with fluent methods)...(add orderBy/orderBydesc if you want)...
//  - and then just put end of filters / or end of only select()  toSingle() / or toList()
//  - you can select one or return List<yourObject> by your filters and orders
//  - also you can batch update or batch delete by using delete/update methods instead of tosingle/tolist methods
//    Enjoy.. Huseyin Tokpunar

// BEGIN TABLES
// Milestone TABLE
class TableMilestone extends SqfEntityTableBase {
  TableMilestone() {
    // declare properties of EntityTable
    tableName = 'milestones';
    primaryKeyName = 'id';
    primaryKeyType = PrimaryKeyType.integer_auto_incremental;
    useSoftDeleting = false;
    // when useSoftDeleting is true, creates a field named 'isDeleted' on the table, and set to '1' this field when item deleted (does not hard delete)

    // declare fields
    fields = [
      SqfEntityFieldBase('type', DbType.text),
      SqfEntityFieldBase('description', DbType.text),
      SqfEntityFieldBase('date', DbType.datetimeUtc,
          minValue: DateTime.parse('1900-01-01')),
      SqfEntityFieldBase('created', DbType.datetime,
          defaultValue: DateTime.now(), minValue: DateTime.parse('1900-01-01')),
    ];
    super.init();
  }
  static SqfEntityTableBase? _instance;
  static SqfEntityTableBase get getInstance {
    return _instance = _instance ?? TableMilestone();
  }
}
// END TABLES

// BEGIN SEQUENCES
// milestoneIdentity SEQUENCE
class SequenceMilestoneidentitySequence extends SqfEntitySequenceBase {
  SequenceMilestoneidentitySequence() {
    sequenceName = 'milestoneIdentity';
    maxValue =
        9007199254740991; /* optional. default is max int (9.223.372.036.854.775.807) */
    cycle = false; /* optional. default is false; */
    minValue = 0; /* optional. default is 0 */
    incrementBy = 1; /* optional. default is 1 */
    startWith = 0; /* optional. default is 0 */
    super.init();
  }
  static SequenceMilestoneidentitySequence? _instance;
  static SequenceMilestoneidentitySequence get getInstance {
    return _instance = _instance ?? SequenceMilestoneidentitySequence();
  }
}
// END SEQUENCES

// BEGIN DATABASE MODEL
class MilestoneModel extends SqfEntityModelProvider {
  MilestoneModel() {
    databaseName = myDbModel.databaseName;
    password = myDbModel.password;
    dbVersion = myDbModel.dbVersion;
    preSaveAction = myDbModel.preSaveAction;
    logFunction = myDbModel.logFunction;
    databaseTables = [
      TableMilestone.getInstance,
    ];

    sequences = [
      SequenceMilestoneidentitySequence.getInstance,
    ];

    bundledDatabasePath = myDbModel
        .bundledDatabasePath; //'assets/sample.db'; // This value is optional. When bundledDatabasePath is empty then EntityBase creats a new database when initializing the database
    databasePath = myDbModel.databasePath;
  }
  Map<String, dynamic> getControllers() {
    final controllers = <String, dynamic>{};

    return controllers;
  }
}
// END DATABASE MODEL

// BEGIN ENTITIES
// region Milestone
class Milestone extends TableBase {
  Milestone({this.id, this.type, this.description, this.date, this.created}) {
    _setDefaultValues();
    softDeleteActivated = false;
  }
  Milestone.withFields(this.type, this.description, this.date, this.created) {
    _setDefaultValues();
  }
  Milestone.withId(
      this.id, this.type, this.description, this.date, this.created) {
    _setDefaultValues();
  }
  // fromMap v2.0
  Milestone.fromMap(Map<String, dynamic> o, {bool setDefaultValues = true}) {
    if (setDefaultValues) {
      _setDefaultValues();
    }
    id = int.tryParse(o['id'].toString());
    if (o['type'] != null) {
      type = o['type'].toString();
    }
    if (o['description'] != null) {
      description = o['description'].toString();
    }
    if (o['date'] != null) {
      date = int.tryParse(o['date'].toString()) != null
          ? DateTime.fromMillisecondsSinceEpoch(
              int.tryParse(o['date'].toString())!,
              isUtc: true)
          : DateTime.tryParse(o['date'].toString());
    }
    if (o['created'] != null) {
      created = int.tryParse(o['created'].toString()) != null
          ? DateTime.fromMillisecondsSinceEpoch(
              int.tryParse(o['created'].toString())!)
          : DateTime.tryParse(o['created'].toString());
    }
  }
  // FIELDS (Milestone)
  int? id;
  String? type;
  String? description;
  DateTime? date;
  DateTime? created;

  // end FIELDS (Milestone)

  static const bool _softDeleteActivated = false;
  MilestoneManager? __mnMilestone;

  MilestoneManager get _mnMilestone {
    return __mnMilestone = __mnMilestone ?? MilestoneManager();
  }

  // METHODS
  @override
  Map<String, dynamic> toMap(
      {bool forQuery = false, bool forJson = false, bool forView = false}) {
    final map = <String, dynamic>{};
    map['id'] = id;
    if (type != null || !forView) {
      map['type'] = type;
    }
    if (description != null || !forView) {
      map['description'] = description;
    }
    if (date != null) {
      map['date'] = forJson
          ? date!.toUtc().toString()
          : forQuery
              ? date!.millisecondsSinceEpoch
              : date;
    } else if (date != null || !forView) {
      map['date'] = null;
    }
    if (created != null) {
      map['created'] = forJson
          ? created!.toString()
          : forQuery
              ? created!.millisecondsSinceEpoch
              : created;
    } else if (created != null || !forView) {
      map['created'] = null;
    }

    return map;
  }

  @override
  Future<Map<String, dynamic>> toMapWithChildren(
      [bool forQuery = false,
      bool forJson = false,
      bool forView = false]) async {
    final map = <String, dynamic>{};
    map['id'] = id;
    if (type != null || !forView) {
      map['type'] = type;
    }
    if (description != null || !forView) {
      map['description'] = description;
    }
    if (date != null) {
      map['date'] = forJson
          ? date!.toUtc().toString()
          : forQuery
              ? date!.millisecondsSinceEpoch
              : date;
    } else if (date != null || !forView) {
      map['date'] = null;
    }
    if (created != null) {
      map['created'] = forJson
          ? created!.toString()
          : forQuery
              ? created!.millisecondsSinceEpoch
              : created;
    } else if (created != null || !forView) {
      map['created'] = null;
    }

    return map;
  }

  /// This method returns Json String [Milestone]
  @override
  String toJson() {
    return json.encode(toMap(forJson: true));
  }

  /// This method returns Json String [Milestone]
  @override
  Future<String> toJsonWithChilds() async {
    return json.encode(await toMapWithChildren(false, true));
  }

  @override
  List<dynamic> toArgs() {
    return [
      type,
      description,
      date != null ? date!.millisecondsSinceEpoch : null,
      created != null ? created!.millisecondsSinceEpoch : null
    ];
  }

  @override
  List<dynamic> toArgsWithIds() {
    return [
      id,
      type,
      description,
      date != null ? date!.millisecondsSinceEpoch : null,
      created != null ? created!.millisecondsSinceEpoch : null
    ];
  }

  static Future<List<Milestone>?> fromWebUrl(Uri uri,
      {Map<String, String>? headers}) async {
    try {
      final response = await http.get(uri, headers: headers);
      return await fromJson(response.body);
    } catch (e) {
      debugPrint(
          'SQFENTITY ERROR Milestone.fromWebUrl: ErrorMessage: ${e.toString()}');
      return null;
    }
  }

  Future<http.Response> postUrl(Uri uri, {Map<String, String>? headers}) {
    return http.post(uri, headers: headers, body: toJson());
  }

  static Future<List<Milestone>> fromJson(String jsonBody) async {
    final Iterable list = await json.decode(jsonBody) as Iterable;
    var objList = <Milestone>[];
    try {
      objList = list
          .map((milestone) =>
              Milestone.fromMap(milestone as Map<String, dynamic>))
          .toList();
    } catch (e) {
      debugPrint(
          'SQFENTITY ERROR Milestone.fromJson: ErrorMessage: ${e.toString()}');
    }
    return objList;
  }

  static Future<List<Milestone>> fromMapList(List<dynamic> data,
      {bool preload = false,
      List<String>? preloadFields,
      bool loadParents = false,
      List<String>? loadedFields,
      bool setDefaultValues = true}) async {
    final List<Milestone> objList = <Milestone>[];
    loadedFields = loadedFields ?? [];
    for (final map in data) {
      final obj = Milestone.fromMap(map as Map<String, dynamic>,
          setDefaultValues: setDefaultValues);

      objList.add(obj);
    }
    return objList;
  }

  /// returns Milestone by ID if exist, otherwise returns null
  /// Primary Keys: int? id
  /// bool preload: if true, loads all related child objects (Set preload to true if you want to load all fields related to child or parent)
  /// ex: getById(preload:true) -> Loads all related objects
  /// List<String> preloadFields: specify the fields you want to preload (preload parameter's value should also be "true")
  /// ex: getById(preload:true, preloadFields:['plField1','plField2'... etc])  -> Loads only certain fields what you specified
  /// bool loadParents: if true, loads all parent objects until the object has no parent

  /// <returns>returns [Milestone] if exist, otherwise returns null
  Future<Milestone?> getById(int? id,
      {bool preload = false,
      List<String>? preloadFields,
      bool loadParents = false,
      List<String>? loadedFields}) async {
    if (id == null) {
      return null;
    }
    Milestone? obj;
    final data = await _mnMilestone.getById([id]);
    if (data.length != 0) {
      obj = Milestone.fromMap(data[0] as Map<String, dynamic>);
    } else {
      obj = null;
    }
    return obj;
  }

  /// Saves the (Milestone) object. If the id field is null, saves as a new record and returns new id, if id is not null then updates record
  /// ignoreBatch = true as a default. Set ignoreBatch to false if you run more than one save() operation those are between batchStart and batchCommit
  /// <returns>Returns id
  @override
  Future<int?> save({bool ignoreBatch = true}) async {
    if (id == null || id == 0) {
      id = await _mnMilestone.insert(this, ignoreBatch);
    } else {
      await _mnMilestone.update(this);
    }

    return id;
  }

  /// Saves the (Milestone) object. If the id field is null, saves as a new record and returns new id, if id is not null then updates record
  /// ignoreBatch = true as a default. Set ignoreBatch to false if you run more than one save() operation those are between batchStart and batchCommit
  /// <returns>Returns id
  @override
  Future<int?> saveOrThrow({bool ignoreBatch = true}) async {
    if (id == null || id == 0) {
      id = await _mnMilestone.insertOrThrow(this, ignoreBatch);

      isInsert = true;
    } else {
      // id= await _upsert(); // removed in sqfentity_gen 1.3.0+6
      await _mnMilestone.updateOrThrow(this);
    }

    return id;
  }

  /// saveAs Milestone. Returns a new Primary Key value of Milestone

  /// <returns>Returns a new Primary Key value of Milestone
  @override
  Future<int?> saveAs({bool ignoreBatch = true}) async {
    id = null;

    return save(ignoreBatch: ignoreBatch);
  }

  /// saveAll method saves the sent List<Milestone> as a bulk in one transaction
  /// Returns a <List<BoolResult>>
  static Future<List<dynamic>> saveAll(List<Milestone> milestones,
      {bool? exclusive, bool? noResult, bool? continueOnError}) async {
    List<dynamic>? result = [];
    // If there is no open transaction, start one
    final isStartedBatch = await MilestoneModel().batchStart();
    for (final obj in milestones) {
      await obj.save(ignoreBatch: false);
    }
    if (!isStartedBatch) {
      result = await MilestoneModel().batchCommit(
          exclusive: exclusive,
          noResult: noResult,
          continueOnError: continueOnError);
      for (int i = 0; i < milestones.length; i++) {
        if (milestones[i].id == null) {
          milestones[i].id = result![i] as int;
        }
      }
    }
    return result!;
  }

  /// Updates if the record exists, otherwise adds a new row
  /// <returns>Returns id
  @override
  Future<int?> upsert({bool ignoreBatch = true}) async {
    try {
      final result = await _mnMilestone.rawInsert(
          'INSERT OR REPLACE INTO milestones (id, type, description, date, created)  VALUES (?,?,?,?,?)',
          [
            id,
            type,
            description,
            date != null ? date!.millisecondsSinceEpoch : null,
            created != null ? created!.millisecondsSinceEpoch : null
          ],
          ignoreBatch);
      if (result! > 0) {
        saveResult = BoolResult(
            success: true,
            successMessage: 'Milestone id=$id updated successfully');
      } else {
        saveResult = BoolResult(
            success: false, errorMessage: 'Milestone id=$id did not update');
      }
      return id;
    } catch (e) {
      saveResult = BoolResult(
          success: false,
          errorMessage: 'Milestone Save failed. Error: ${e.toString()}');
      return null;
    }
  }

  /// inserts or replaces the sent List<<Milestone>> as a bulk in one transaction.
  /// upsertAll() method is faster then saveAll() method. upsertAll() should be used when you are sure that the primary key is greater than zero
  /// Returns a BoolCommitResult
  @override
  Future<BoolCommitResult> upsertAll(List<Milestone> milestones,
      {bool? exclusive, bool? noResult, bool? continueOnError}) async {
    final results = await _mnMilestone.rawInsertAll(
        'INSERT OR REPLACE INTO milestones (id, type, description, date, created)  VALUES (?,?,?,?,?)',
        milestones,
        exclusive: exclusive,
        noResult: noResult,
        continueOnError: continueOnError);
    return results;
  }

  /// Deletes Milestone

  /// <returns>BoolResult res.success= true (Deleted), false (Could not be deleted)
  @override
  Future<BoolResult> delete([bool hardDelete = false]) async {
    debugPrint('SQFENTITIY: delete Milestone invoked (id=$id)');
    if (!_softDeleteActivated || hardDelete) {
      return _mnMilestone
          .delete(QueryParams(whereString: 'id=?', whereArguments: [id]));
    } else {
      return _mnMilestone.updateBatch(
          QueryParams(whereString: 'id=?', whereArguments: [id]),
          {'isDeleted': 1});
    }
  }

  @override
  Future<BoolResult> recover([bool recoverChilds = true]) {
    // not implemented because:
    final msg =
        'set useSoftDeleting:true in the table definition of [Milestone] to use this feature';
    throw UnimplementedError(msg);
  }

  @override
  MilestoneFilterBuilder select(
      {List<String>? columnsToSelect, bool? getIsDeleted}) {
    return MilestoneFilterBuilder(this, getIsDeleted)
      ..qparams.selectColumns = columnsToSelect;
  }

  @override
  MilestoneFilterBuilder distinct(
      {List<String>? columnsToSelect, bool? getIsDeleted}) {
    return MilestoneFilterBuilder(this, getIsDeleted)
      ..qparams.selectColumns = columnsToSelect
      ..qparams.distinct = true;
  }

  void _setDefaultValues() {
    created = created ?? DateTime.now();
  }

  @override
  void rollbackPk() {
    if (isInsert == true) {
      id = null;
    }
  }

  // END METHODS
  // BEGIN CUSTOM CODE
  /*
      you can define customCode property of your SqfEntityTable constant. For example:
      const tablePerson = SqfEntityTable(
      tableName: 'person',
      primaryKeyName: 'id',
      primaryKeyType: PrimaryKeyType.integer_auto_incremental,
      fields: [
        SqfEntityField('firstName', DbType.text),
        SqfEntityField('lastName', DbType.text),
      ],
      customCode: '''
       String fullName()
       { 
         return '$firstName $lastName';
       }
      ''');
     */
  // END CUSTOM CODE
}
// endregion milestone

// region MilestoneField
class MilestoneField extends FilterBase {
  MilestoneField(MilestoneFilterBuilder milestoneFB) : super(milestoneFB);

  @override
  MilestoneFilterBuilder equals(dynamic pValue) {
    return super.equals(pValue) as MilestoneFilterBuilder;
  }

  @override
  MilestoneFilterBuilder equalsOrNull(dynamic pValue) {
    return super.equalsOrNull(pValue) as MilestoneFilterBuilder;
  }

  @override
  MilestoneFilterBuilder isNull() {
    return super.isNull() as MilestoneFilterBuilder;
  }

  @override
  MilestoneFilterBuilder contains(dynamic pValue) {
    return super.contains(pValue) as MilestoneFilterBuilder;
  }

  @override
  MilestoneFilterBuilder startsWith(dynamic pValue) {
    return super.startsWith(pValue) as MilestoneFilterBuilder;
  }

  @override
  MilestoneFilterBuilder endsWith(dynamic pValue) {
    return super.endsWith(pValue) as MilestoneFilterBuilder;
  }

  @override
  MilestoneFilterBuilder between(dynamic pFirst, dynamic pLast) {
    return super.between(pFirst, pLast) as MilestoneFilterBuilder;
  }

  @override
  MilestoneFilterBuilder greaterThan(dynamic pValue) {
    return super.greaterThan(pValue) as MilestoneFilterBuilder;
  }

  @override
  MilestoneFilterBuilder lessThan(dynamic pValue) {
    return super.lessThan(pValue) as MilestoneFilterBuilder;
  }

  @override
  MilestoneFilterBuilder greaterThanOrEquals(dynamic pValue) {
    return super.greaterThanOrEquals(pValue) as MilestoneFilterBuilder;
  }

  @override
  MilestoneFilterBuilder lessThanOrEquals(dynamic pValue) {
    return super.lessThanOrEquals(pValue) as MilestoneFilterBuilder;
  }

  @override
  MilestoneFilterBuilder inValues(dynamic pValue) {
    return super.inValues(pValue) as MilestoneFilterBuilder;
  }

  @override
  MilestoneField get not {
    return super.not as MilestoneField;
  }
}
// endregion MilestoneField

// region MilestoneFilterBuilder
class MilestoneFilterBuilder extends ConjunctionBase {
  MilestoneFilterBuilder(Milestone obj, bool? getIsDeleted)
      : super(obj, getIsDeleted) {
    _mnMilestone = obj._mnMilestone;
    _softDeleteActivated = obj.softDeleteActivated;
  }

  bool _softDeleteActivated = false;
  MilestoneManager? _mnMilestone;

  /// put the sql keyword 'AND'
  @override
  MilestoneFilterBuilder get and {
    super.and;
    return this;
  }

  /// put the sql keyword 'OR'
  @override
  MilestoneFilterBuilder get or {
    super.or;
    return this;
  }

  /// open parentheses
  @override
  MilestoneFilterBuilder get startBlock {
    super.startBlock;
    return this;
  }

  /// String whereCriteria, write raw query without 'where' keyword. Like this: 'field1 like 'test%' and field2 = 3'
  @override
  MilestoneFilterBuilder where(String? whereCriteria,
      {dynamic parameterValue}) {
    super.where(whereCriteria, parameterValue: parameterValue);
    return this;
  }

  /// page = page number,
  /// pagesize = row(s) per page
  @override
  MilestoneFilterBuilder page(int page, int pagesize) {
    super.page(page, pagesize);
    return this;
  }

  /// int count = LIMIT
  @override
  MilestoneFilterBuilder top(int count) {
    super.top(count);
    return this;
  }

  /// close parentheses
  @override
  MilestoneFilterBuilder get endBlock {
    super.endBlock;
    return this;
  }

  /// argFields might be String or List<String>.
  /// Example 1: argFields='name, date'
  /// Example 2: argFields = ['name', 'date']
  @override
  MilestoneFilterBuilder orderBy(dynamic argFields) {
    super.orderBy(argFields);
    return this;
  }

  /// argFields might be String or List<String>.
  /// Example 1: argFields='field1, field2'
  /// Example 2: argFields = ['field1', 'field2']
  @override
  MilestoneFilterBuilder orderByDesc(dynamic argFields) {
    super.orderByDesc(argFields);
    return this;
  }

  /// argFields might be String or List<String>.
  /// Example 1: argFields='field1, field2'
  /// Example 2: argFields = ['field1', 'field2']
  @override
  MilestoneFilterBuilder groupBy(dynamic argFields) {
    super.groupBy(argFields);
    return this;
  }

  /// argFields might be String or List<String>.
  /// Example 1: argFields='name, date'
  /// Example 2: argFields = ['name', 'date']
  @override
  MilestoneFilterBuilder having(dynamic argFields) {
    super.having(argFields);
    return this;
  }

  MilestoneField _setField(
      MilestoneField? field, String colName, DbType dbtype) {
    return MilestoneField(this)
      ..param = DbParameter(
          dbType: dbtype, columnName: colName, wStartBlock: openedBlock);
  }

  MilestoneField? _id;
  MilestoneField get id {
    return _id = _setField(_id, 'id', DbType.integer);
  }

  MilestoneField? _type;
  MilestoneField get type {
    return _type = _setField(_type, 'type', DbType.text);
  }

  MilestoneField? _description;
  MilestoneField get description {
    return _description = _setField(_description, 'description', DbType.text);
  }

  MilestoneField? _date;
  MilestoneField get date {
    return _date = _setField(_date, 'date', DbType.datetimeUtc);
  }

  MilestoneField? _created;
  MilestoneField get created {
    return _created = _setField(_created, 'created', DbType.datetime);
  }

  /// Deletes List<Milestone> bulk by query
  ///
  /// <returns>BoolResult res.success= true (Deleted), false (Could not be deleted)
  @override
  Future<BoolResult> delete([bool hardDelete = false]) async {
    buildParameters();
    var r = BoolResult(success: false);

    if (_softDeleteActivated && !hardDelete) {
      r = await _mnMilestone!.updateBatch(qparams, {'isDeleted': 1});
    } else {
      r = await _mnMilestone!.delete(qparams);
    }
    return r;
  }

  /// using:
  /// update({'fieldName': Value})
  /// fieldName must be String. Value is dynamic, it can be any of the (int, bool, String.. )
  @override
  Future<BoolResult> update(Map<String, dynamic> values) {
    buildParameters();
    if (qparams.limit! > 0 || qparams.offset! > 0) {
      qparams.whereString =
          'id IN (SELECT id from milestones ${qparams.whereString!.isNotEmpty ? 'WHERE ${qparams.whereString}' : ''}${qparams.limit! > 0 ? ' LIMIT ${qparams.limit}' : ''}${qparams.offset! > 0 ? ' OFFSET ${qparams.offset}' : ''})';
    }
    return _mnMilestone!.updateBatch(qparams, values);
  }

  /// This method always returns [Milestone] Obj if exist, otherwise returns null
  /// bool preload: if true, loads all related child objects (Set preload to true if you want to load all fields related to child or parent)
  /// ex: toSingle(preload:true) -> Loads all related objects
  /// List<String> preloadFields: specify the fields you want to preload (preload parameter's value should also be "true")
  /// ex: toSingle(preload:true, preloadFields:['plField1','plField2'... etc])  -> Loads only certain fields what you specified
  /// bool loadParents: if true, loads all parent objects until the object has no parent

  /// <returns> Milestone?
  @override
  Future<Milestone?> toSingle(
      {bool preload = false,
      List<String>? preloadFields,
      bool loadParents = false,
      List<String>? loadedFields}) async {
    buildParameters(pSize: 1);
    final objFuture = _mnMilestone!.toList(qparams);
    final data = await objFuture;
    Milestone? obj;
    if (data.isNotEmpty) {
      obj = Milestone.fromMap(data[0] as Map<String, dynamic>);
    } else {
      obj = null;
    }
    return obj;
  }

  /// This method always returns [Milestone]
  /// bool preload: if true, loads all related child objects (Set preload to true if you want to load all fields related to child or parent)
  /// ex: toSingle(preload:true) -> Loads all related objects
  /// List<String> preloadFields: specify the fields you want to preload (preload parameter's value should also be "true")
  /// ex: toSingle(preload:true, preloadFields:['plField1','plField2'... etc])  -> Loads only certain fields what you specified
  /// bool loadParents: if true, loads all parent objects until the object has no parent

  /// <returns> Milestone?
  @override
  Future<Milestone> toSingleOrDefault(
      {bool preload = false,
      List<String>? preloadFields,
      bool loadParents = false,
      List<String>? loadedFields}) async {
    return await toSingle(
            preload: preload,
            preloadFields: preloadFields,
            loadParents: loadParents,
            loadedFields: loadedFields) ??
        Milestone();
  }

  /// This method returns int. [Milestone]
  /// <returns>int
  @override
  Future<int> toCount([VoidCallback Function(int c)? milestoneCount]) async {
    buildParameters();
    qparams.selectColumns = ['COUNT(1) AS CNT'];
    final milestonesFuture = await _mnMilestone!.toList(qparams);
    final int count = milestonesFuture[0]['CNT'] as int;
    if (milestoneCount != null) {
      milestoneCount(count);
    }
    return count;
  }

  /// This method returns List<Milestone> [Milestone]
  /// bool preload: if true, loads all related child objects (Set preload to true if you want to load all fields related to child or parent)
  /// ex: toList(preload:true) -> Loads all related objects
  /// List<String> preloadFields: specify the fields you want to preload (preload parameter's value should also be "true")
  /// ex: toList(preload:true, preloadFields:['plField1','plField2'... etc])  -> Loads only certain fields what you specified
  /// bool loadParents: if true, loads all parent objects until the object has no parent

  /// <returns>List<Milestone>
  @override
  Future<List<Milestone>> toList(
      {bool preload = false,
      List<String>? preloadFields,
      bool loadParents = false,
      List<String>? loadedFields}) async {
    final data = await toMapList();
    final List<Milestone> milestonesData = await Milestone.fromMapList(data,
        preload: preload,
        preloadFields: preloadFields,
        loadParents: loadParents,
        loadedFields: loadedFields,
        setDefaultValues: qparams.selectColumns == null);
    return milestonesData;
  }

  /// This method returns Json String [Milestone]
  @override
  Future<String> toJson() async {
    final list = <dynamic>[];
    final data = await toList();
    for (var o in data) {
      list.add(o.toMap(forJson: true));
    }
    return json.encode(list);
  }

  /// This method returns Json String. [Milestone]
  @override
  Future<String> toJsonWithChilds() async {
    final list = <dynamic>[];
    final data = await toList();
    for (var o in data) {
      list.add(await o.toMapWithChildren(false, true));
    }
    return json.encode(list);
  }

  /// This method returns List<dynamic>. [Milestone]
  /// <returns>List<dynamic>
  @override
  Future<List<dynamic>> toMapList() async {
    buildParameters();
    return await _mnMilestone!.toList(qparams);
  }

  /// This method returns Primary Key List SQL and Parameters retVal = Map<String,dynamic>. [Milestone]
  /// retVal['sql'] = SQL statement string, retVal['args'] = whereArguments List<dynamic>;
  /// <returns>List<String>
  @override
  Map<String, dynamic> toListPrimaryKeySQL([bool buildParams = true]) {
    final Map<String, dynamic> _retVal = <String, dynamic>{};
    if (buildParams) {
      buildParameters();
    }
    _retVal['sql'] = 'SELECT `id` FROM milestones WHERE ${qparams.whereString}';
    _retVal['args'] = qparams.whereArguments;
    return _retVal;
  }

  /// This method returns Primary Key List<int>.
  /// <returns>List<int>
  @override
  Future<List<int>> toListPrimaryKey([bool buildParams = true]) async {
    if (buildParams) {
      buildParameters();
    }
    final List<int> idData = <int>[];
    qparams.selectColumns = ['id'];
    final idFuture = await _mnMilestone!.toList(qparams);

    final int count = idFuture.length;
    for (int i = 0; i < count; i++) {
      idData.add(idFuture[i]['id'] as int);
    }
    return idData;
  }

  /// Returns List<dynamic> for selected columns. Use this method for 'groupBy' with min,max,avg..  [Milestone]
  /// Sample usage: (see EXAMPLE 4.2 at https://github.com/hhtokpinar/sqfEntity#group-by)
  @override
  Future<List<dynamic>> toListObject() async {
    buildParameters();

    final objectFuture = _mnMilestone!.toList(qparams);

    final List<dynamic> objectsData = <dynamic>[];
    final data = await objectFuture;
    final int count = data.length;
    for (int i = 0; i < count; i++) {
      objectsData.add(data[i]);
    }
    return objectsData;
  }

  /// Returns List<String> for selected first column
  /// Sample usage: await Milestone.select(columnsToSelect: ['columnName']).toListString()
  @override
  Future<List<String>> toListString(
      [VoidCallback Function(List<String> o)? listString]) async {
    buildParameters();

    final objectFuture = _mnMilestone!.toList(qparams);

    final List<String> objectsData = <String>[];
    final data = await objectFuture;
    final int count = data.length;
    for (int i = 0; i < count; i++) {
      objectsData.add(data[i][qparams.selectColumns![0]].toString());
    }
    if (listString != null) {
      listString(objectsData);
    }
    return objectsData;
  }
}
// endregion MilestoneFilterBuilder

// region MilestoneFields
class MilestoneFields {
  static TableField? _fId;
  static TableField get id {
    return _fId = _fId ?? SqlSyntax.setField(_fId, 'id', DbType.integer);
  }

  static TableField? _fType;
  static TableField get type {
    return _fType = _fType ?? SqlSyntax.setField(_fType, 'type', DbType.text);
  }

  static TableField? _fDescription;
  static TableField get description {
    return _fDescription = _fDescription ??
        SqlSyntax.setField(_fDescription, 'description', DbType.text);
  }

  static TableField? _fDate;
  static TableField get date {
    return _fDate =
        _fDate ?? SqlSyntax.setField(_fDate, 'date', DbType.datetimeUtc);
  }

  static TableField? _fCreated;
  static TableField get created {
    return _fCreated =
        _fCreated ?? SqlSyntax.setField(_fCreated, 'created', DbType.datetime);
  }
}
// endregion MilestoneFields

//region MilestoneManager
class MilestoneManager extends SqfEntityProvider {
  MilestoneManager()
      : super(MilestoneModel(),
            tableName: _tableName,
            primaryKeyList: _primaryKeyList,
            whereStr: _whereStr);
  static const String _tableName = 'milestones';
  static const List<String> _primaryKeyList = ['id'];
  static const String _whereStr = 'id=?';
}

//endregion MilestoneManager
/// Region SEQUENCE MilestoneidentitySequence
class MilestoneidentitySequence {
  /// Assigns a new value when it is triggered and returns the new value
  /// returns Future<int>
  Future<int> nextVal([VoidCallback Function(int o)? nextval]) async {
    final val = await MilestoneModelSequenceManager()
        .sequence(SequenceMilestoneidentitySequence.getInstance, true);
    if (nextval != null) {
      nextval(val);
    }
    return val;
  }

  /// Get the current value
  /// returns Future<int>
  Future<int> currentVal([VoidCallback Function(int o)? currentval]) async {
    final val = await MilestoneModelSequenceManager()
        .sequence(SequenceMilestoneidentitySequence.getInstance, false);
    if (currentval != null) {
      currentval(val);
    }
    return val;
  }

  /// Reset sequence to start value
  /// returns start value
  Future<int> reset([VoidCallback Function(int o)? currentval]) async {
    final val = await MilestoneModelSequenceManager().sequence(
        SequenceMilestoneidentitySequence.getInstance, false,
        reset: true);
    if (currentval != null) {
      currentval(val);
    }
    return val;
  }
}

/// End Region SEQUENCE MilestoneidentitySequence

class MilestoneModelSequenceManager extends SqfEntityProvider {
  MilestoneModelSequenceManager() : super(MilestoneModel());
}
// END OF ENTITIES
